### ISSUE TITLE
Транслитерация идентификаторов не нужна

### ISSUE THREAD

**Issue by mixtur** [MicrosoftDocs/cpp-docs.ru-ru#103]
Транслитерация имён параметров и функций в переводе не нужна.  мкгмтиме? саурцтиме? Серьёзно что ли?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: ad7265ed-e3e1-ca2b-3b3f-2e35323e2590
* Version Independent ID: 3c090720-3144-a85a-8e58-b9c3a893dc80
* Content: [gmtime, _gmtime32, _gmtime64](https://docs.microsoft.com/ru-ru/cpp/c-runtime-library/reference/gmtime-gmtime32-gmtime64?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/gmtime-gmtime32-gmtime64.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/c-runtime-library/reference/gmtime-gmtime32-gmtime64.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Спасибо, что помогли нам сделать документы лучше. Исправление должно быть жить завтра днем (10/28) Пожалуйста, простите мой русский. Я использую инструмент переводчика.
#please-close
