### ISSUE TITLE
Ru doc localization

### ISSUE THREAD

**Issue by DenisGZM** [MicrosoftDocs/cpp-docs.ru-ru#108]
Добрый день.
В русскоязычной доке очень много автоматических странных переводов названий типа CObject:: Жетрунтимекласс (CObject::GetRuntimeClass) или CObject::D УМП (CObject::Dump)
Выглядит конечно забавно, но наверно нужно пофиксить :)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 693708aa-09e5-4abf-1db8-c120fda4700b
* Version Independent ID: 9728db3d-d956-4dce-0fbb-86022f395b38
* Content: [CObject, класс](https://docs.microsoft.com/ru-ru/cpp/mfc/reference/cobject-class?view=msvc-160)
* Content Source: [docs/mfc/reference/cobject-class.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/mfc/reference/cobject-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Thank you for pointing this out. I've marked code elements so that machine translation won't try to translate them. The fix should be live by end of day 1/13/2021
