### ISSUE TITLE
Страница не отображается

### ISSUE THREAD

**Issue by alphavector** [MicrosoftDocs/cpp-docs.ru-ru#109]
Страница https://docs.microsoft.com/ru-ru/cpp/get-started/tutorial-console-cpp?view=msvc-160 не отображается

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Создание консольного приложения 'Калькулятор' на C++](https://docs.microsoft.com/ru-ru/cpp/get-started/tutorial-console-cpp?view=msvc-160)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JasonCard Is there a localized build problem with this page?

**Comment by JasonCard** [comment]
@alphavector @corob-msft Thank you for reporting this issue. There was a technical issue in our localization pipeline, causing the moniker range to be outdated for all language, so localized content is not being displayed. I've escalated this issue and will update when resolved.

**Comment by JasonCard** [comment]
@alphavector @corob-msft This issue is now fixed :)
