### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by mikhail-gorbachenko** [MicrosoftDocs/cpp-docs.ru-ru#58]
В русском переводе путаница
Английские локали приведены как ru-RU

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a25b2062-1d8a-a709-dcaa-638f7a1ebc01
* Version Independent ID: d734a773-6beb-305b-96f7-dff303a99567
* Content: [Language Strings](https://docs.microsoft.com/ru-ru/cpp/c-runtime-library/language-strings?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/language-strings.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/c-runtime-library/language-strings.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Здравствуйте, @mikhail-gorbachenko
 Спасибо за отзыв. 
 Мы активно просматриваем комментарии и скоро ответим Вам. 
 С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by lichasu** [comment]
Здравствуйте, @mikhail-gorbachenko 
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. 
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
