### ISSUE TITLE
Не корректно переведенная страница(incorrect translation)

### ISSUE THREAD

**Issue by ale5000** [MicrosoftDocs/cpp-docs.ru-ru#73]
Переведены названия методов класса, например: CAsyncSocket:: Асинкселект, что не является корректным. Class methods Translated by automatic translation(but better if they shouldnt), for example CAsyncSocket:: Асинкселект in Russian version

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 1c11b2e5-1be9-8d75-a063-8e5c769ec7b0
* Version Independent ID: 533b7b93-3e56-787e-6c39-f346e2104ab0
* Content: [Класс CAsyncSocket](https://docs.microsoft.com/ru-ru/cpp/mfc/reference/casyncsocket-class?view=vs-2019#asyncselect)
* Content Source: [docs/mfc/reference/casyncsocket-class.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/mfc/reference/casyncsocket-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @ale5000
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @ale5000  
Спасибо за отзыв. Рассматриваемая страница переведена с использованием машинного перевода, который не всегда идеально понятен. Недавно мы добавили справа на странице функцию «Прочитать на английском», которая позволяет переключиться на английскую версию, не меняя настройки языка. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
