### ISSUE TITLE
тмдест? еинвал? саурцетиме??? 

### ISSUE THREAD

**Issue by aisilu93** [MicrosoftDocs/cpp-docs.ru-ru#75]
Почему на этом сайте, начиная с некоторого недавнего времени, параметры к функциям указаны на транслите?Саурцетиме? Вы серьезно??? Верните, пожалуйста, оригинальные названия параметров, а то с серьезным лицом читать это невозможно, да и разобраться во всем очень тяжело (кому как не вам знать, что названия параметров завязаны на определенные английские слова, которые легче понять и, следовательно, запомнить, если они написаны на языке оригинала)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7ba4cd48-33d2-5e22-37db-392936d00884
* Version Independent ID: b91693b2-f46e-06ad-3097-072233021058
* Content: [gmtime_s, _gmtime32_s, _gmtime64_s](https://docs.microsoft.com/ru-ru/cpp/c-runtime-library/reference/gmtime-s-gmtime32-s-gmtime64-s?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/gmtime-s-gmtime32-s-gmtime64-s.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/c-runtime-library/reference/gmtime-s-gmtime32-s-gmtime64-s.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @aisilu93
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @aisilu93
Спасибо за отзыв. Рассматриваемая страница переведена с использованием машинного перевода, который не всегда идеально понятен. Недавно мы добавили справа на странице функцию «Прочитать на английском», которая позволяет переключиться на английскую версию, не меняя настройки языка. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by aisilu93** [comment]
Я в курсе про переключение языка, но для чего существует документация на русском, если все равно ее нужно читать на английском?.. Я вам сообщаю о проблеме на сайте, что ваш машинный перевод работает некорректно, английские слова переписываются русскими буквами, такого быть не должно, это мешает изучать документацию
