### ISSUE TITLE
CMak & CMAK

### ISSUE THREAD

**Issue by ctpo6** [MicrosoftDocs/cpp-docs.ru-ru#77]
Это так был переведен CMake в русской версии. Рука-лицо.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 781298c5-3bb4-0bd4-06ca-b09517a76ebc
* Version Independent ID: acb60102-701d-ccb2-d138-2ceb35813292
* Content: [Проекты CMake в Visual Studio](https://docs.microsoft.com/ru-ru/cpp/build/cmake-projects-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/build/cmake-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/build/cmake-projects-in-visual-studio.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @ctpo6
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @ctpo6  
Спасибо за отзыв. Рассматриваемая страница переведена с использованием машинного перевода, который не всегда идеально понятен. Недавно мы добавили справа на странице функцию «Прочитать на английском», которая позволяет переключиться на английскую версию, не меняя настройки языка. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
