### ISSUE TITLE
Invalid russian translation

### ISSUE THREAD

**Issue by masscry** [MicrosoftDocs/cpp-docs.ru-ru#78]
There are some issues with automatic translation of this page in Russian:

Method names, parameters, etc transliterated into unreadable mess:

Example:
  Кргн:: Комбинергн

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a72ca4b9-2ee4-fc5b-e072-4453a14f19a0
* Version Independent ID: cbd5e296-5848-28ba-90c7-6993e72686d6
* Content: [Класс Кргн](https://docs.microsoft.com/ru-ru/cpp/mfc/reference/crgn-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/crgn-class.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/mfc/reference/crgn-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @masscry
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @masscry 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Microsoft DOCS International Team
Kind regards,
