### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by OldFaggotGeek** [MicrosoftDocs/cpp-docs.ru-ru#89]
Какой долботряс переводил на русский? В описании первого примера сильно искажён смысл!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a000dbf7-4ebd-8227-41c8-343c8f8a3af5
* Version Independent ID: 38e5a6ab-69ef-8f16-a828-c0f01e297393
* Content: [Оператор switch (C)](https://docs.microsoft.com/ru-ru/cpp/c-language/switch-statement-c?view=vs-2019#feedback)
* Content Source: [docs/c-language/switch-statement-c.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/c-language/switch-statement-c.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @OldFaggotGeek
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Здравствуйте, @OldFaggotGeek!   

Спасибо за отзыв.  

Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/cpp/c-language/switch-statement-c?view=vs-2019#feedback.   

Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы.  

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
