### ISSUE TITLE
Страница не переведена на русский корректно.

### ISSUE THREAD

**Issue by 100ants** [MicrosoftDocs/cpp-docs.ru-ru#90]
&lt;массив&gt;, массив:value_type 😅
Хотя лучше всех - массив::pоинтер 😂

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 9e10e16b-cc2c-291a-eb5a-18a6cbc486a7
* Version Independent ID: a00ddcc6-ae2a-584c-c28b-d4221f428543
* Content: [Класс array (стандартная библиотека C++ )](https://docs.microsoft.com/ru-ru/cpp/standard-library/array-class-stl?view=vs-2019#feedback)
* Content Source: [docs/standard-library/array-class-stl.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/standard-library/array-class-stl.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by srvbpigh** [comment]
Hello, @100ants
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @100ants 

Спасибо за Ваше предложение! 
 

Публикации о проблемах с содержимым, обработанным с помощью машинного перевода, сейчас не принимаются. 

Мы ценим ваши отзывы и предложения, касающиеся переведенного вручную содержимого. Мы используем их для обучения подсистем машинного перевода. Со временем это позволит улучшить качество как машинного, так и ручного перевода. 

Статьи, переведенные вручную, можно отличить от статей, обработанных с помощью машинного перевода, по значению метаданных ms.translationtype, которое равно "HT" (при использовании машинного перевода — "MT") в заголовке каждого файла с содержимым. 

Большое спасибо за поддержку! 

Microsoft DOCS Global Experience Team
