### ISSUE TITLE
#89

### ISSUE THREAD

**Issue by OldFaggotGeek** [MicrosoftDocs/cpp-docs.ru-ru#91]
#89 - закрыли, написав шаблонную "отписку", но в описании первого примера по-прежнему бред!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a000dbf7-4ebd-8227-41c8-343c8f8a3af5
* Version Independent ID: 38e5a6ab-69ef-8f16-a828-c0f01e297393
* Content: [Оператор switch (C)](https://docs.microsoft.com/ru-ru/cpp/c-language/switch-statement-c?view=vs-2019#feedback)
* Content Source: [docs/c-language/switch-statement-c.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/c-language/switch-statement-c.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @OldFaggotGeek
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #2138](https://github.com/MicrosoftDocs/cpp-docs/issues/2138) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Здравствуйте, @OldFaggotGeek!  

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/cpp-docs/issues/2138.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
