### ISSUE TITLE
Имена методов переведены на русский машинным переводом

### ISSUE THREAD

**Issue by sashaqwert** [MicrosoftDocs/cpp-docs.ru-ru#92]
На этой странице имена методов переведены машинным переводом (из-за чего эта часть страницы становится неактуальной)
CObArray::Добавить               Добавляет элемент в конец массива. При необходимости размер массива увеличивается.
CObArray::Приложение         Добавляет другой массив к массиву. При необходимости размер массива увеличивается.

Если даёте машинному переводу, то хотя бы исключите те места, где точно не надо переводить (имена методова, классов и. т. д.)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 6e5cdd99-113f-4f02-3bf6-5d1d55a69089
* Version Independent ID: 299ec27c-0c12-76cd-d1bc-073565a78337
* Content: [Класс CObArray](https://docs.microsoft.com/ru-ru/cpp/mfc/reference/cobarray-class?view=vs-2017)
* Content Source: [docs/mfc/reference/cobarray-class.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/mfc/reference/cobarray-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by srvbpigh** [comment]
Hello, @sashaqwert
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @sashaqwert 

Спасибо за Ваше предложение! 

Публикации о проблемах с содержимым, обработанным с помощью машинного перевода, сейчас не принимаются. 

Мы ценим ваши отзывы и предложения, касающиеся переведенного вручную содержимого. Мы используем их для обучения подсистем машинного перевода. Со временем это позволит улучшить качество как машинного, так и ручного перевода. 

Статьи, переведенные вручную, можно отличить от статей, обработанных с помощью машинного перевода, по значению метаданных ms.translationtype, которое равно "HT" (при использовании машинного перевода — "MT") в заголовке каждого файла с содержимым. 

Большое спасибо за поддержку! 

Microsoft DOCS Global Experience Team
