### ISSUE TITLE
Отключение всех предупреждений для сторонних библиотек

### ISSUE THREAD

**Issue by Unicornum** [MicrosoftDocs/cpp-docs.ru-ru#93]
Не описано, каким образом (включив в настройках проекта wall для своего кода) отключить все предупреждения для заголовочных файлов сторонних библиотек (включая стандартную библиотеку!) в одном месте сразу для всего проекта/решения.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 9651a718-4fc5-35ea-f5d8-b3d4fc355639
* Version Independent ID: be36f8da-7c38-53c7-7d25-c9ea1f0f6755
* Content: [warning - прагма](https://docs.microsoft.com/ru-ru/cpp/preprocessor/warning?view=vs-2019#feedback)
* Content Source: [docs/preprocessor/warning.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/preprocessor/warning.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @Unicornum
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #2195](https://github.com/MicrosoftDocs/cpp-docs/issues/2195) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Здравствуйте, @Unicornum!  

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/cpp-docs/issues/2195.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
