### ISSUE TITLE
Обьясните пожалуйста.

### ISSUE THREAD

**Issue by baltaevamin** [MicrosoftDocs/cpp-docs.ru-ru#95]
В первом примере,в начале темы.
b = 6
a = 3
b %= a;      // b is 6;   в примере правильно?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 1fb7e11f-cd0d-5e4d-fcf2-6b1060b7586c
* Version Independent ID: 90046753-8233-1a30-09d8-126f8350b3fc
* Content: [Операторы присваивания](https://docs.microsoft.com/ru-ru/cpp/cpp/assignment-operators?view=vs-2019#feedback)
* Content Source: [docs/cpp/assignment-operators.md](https://github.com/MicrosoftDocs/cpp-docs.ru-ru/blob/live/docs/cpp/assignment-operators.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @baltaevamin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Здравствуйте, @baltaevamin!  

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/cpp-docs/issues/2214.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
